### ISSUE TITLE
Docker Swarm?

### ISSUE THREAD

**Issue by ZYecho** [daolinet/daolinet#19]
hello,
Can you explain why not use Docker1.12 with Docker swarm mode(SwarmKit) while you choose the Docker Swarm?

**Comment by frankruizhi** [comment]
Docker swarm mode  does not support the third party network for the present,only the Docker Swarm supports

**Comment by ZYecho** [comment]
thanks a lot.

**Comment by frankruizhi** [comment]
More specific information about the swarm mode ,please have a reference to this link: https://gist.github.com/gkvijay/e8e8f2a6a00c9887fb2abfb0adf742b3
